"""
Generated by ChatGPT using the following prompt:

Write a python function that reads from a raw question file in question/paralympics_raw.csv to a dataframe

"""
import pandas as pd

def read_paralympics_data(file_path):
    try:
        # Read the CSV file into a Pandas DataFrame
        df = pd.read_csv(file_path)

        # Optionally, you can do further question manipulation or analysis here

        return df
    except FileNotFoundError:
        print(f"File not found: {file_path}")
        return None
    except Exception as e:
        print(f"An error occurred: {str(e)}")
        return None

# Specify the path to your raw question file
file_path = "question/paralympics_raw.csv"

# Call the function to read the question into a DataFrame
paralympics_df = read_paralympics_data(file_path)

if paralympics_df is not None:
    # You now have your question in the 'paralympics_df' DataFrame
    # You can perform various operations on this DataFrame for question analysis or manipulation
    print(paralympics_df.head())  # Display the first few rows as a sample