
/**
 * generated by ChatGPT
 */
export const formatCurrency = (
    value: number,
    currencyCode: string,
    locale = "en-US"
  ) => {
    return new Intl.NumberFormat(locale, {
      style: "currency",
      currency: currencyCode,
    }).format(value);
  };

console.log(formatCurrency(1234.56, "USD", "en-US")); // "$1,234.56"
console.log(formatCurrency(1234.56, "EUR", "de-DE")); // "1.234,56 €"
console.log(formatCurrency(1234.56, "JPY", "ja-JP")); // "￥1,235"
console.log(formatCurrency(1234.56, "GBP", "en-GB")); // "£1,234.56"
console.log(formatCurrency(1234.56, "CNY", "zh-CN")); // "￥1,234.56"
