#include <iostream>
#include <vector>
#include <algorithm>
#include <limits>

using namespace std;

int main() {
    int n;
    cin >> n;
    vector<int> l(n);
    for (int i = 0; i < n; ++i) {
        cin >> l[i];
    }

    int min_val = l[0];
    int max_diff = numeric_limits<int>::min();
    for (int i = 1; i < n; ++i) {
        max_diff = max(max_diff, l[i] - min_val);
        min_val = min(min_val, l[i]);
    }

    cout << max_diff << endl;
    return 0;
}

// all are generated by chatGPT