#!/usr/bin/env python3

# General outline and most comments generated by ChatGPT 3.5
def CreateMolecules(file):
    """
    This function returns a list of Molecules that have been read from a file
    """
    # Preliminary Data
    from Molecule import Molecule
    Mols = []

    # Create empty list that will be returned
    with open(file, 'r') as file:
        # Read each line in the file
        for line in file:
            # Remove leading/trailing whitespaces and newline characters
            files = line.strip()
            files = files.split()
            # Create an instance of the Molecule class with the file_name parameter
            Mols.append(Molecule(files[0],files[1]))

    # Return list of molecules
    return Mols