# The function below was generated by ChatGPT

def look_and_say(number):
    result = ""
    count = 1

    for i in range(1, len(number)):
        if number[i] == number[i - 1]:
            count += 1
        else:
            result += str(count) + number[i - 1]
            count = 1

    result += str(count) + number[-1]
    return result

number = '1113122113'
for _ in range(50):
    number = look_and_say(number)

print(len(number))