// Function generated by Copilot - thank you :-)
function checkCSSHighlightAndAdd() {

    if(cssRuleExistsForHighlight === false){
        console.log("CSS rule not found, adding it now");

        // Create a new style element
        const style = document.createElement('style');
        // Add the CSS rule to the style element
        style.textContent = `
        ::highlight(search-result-highlight) {
            background-color: yellow;
            color: black;
          }
        `;

        // Append the style element to the head of the document
        document.head.append(style);

        cssRuleExistsForHighlight = true;
    }
}