########################
# Generated by ChatGPT #
########################
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

def generate_samples(num_stocks, num_samples, mu, sigma):
    return np.random.normal(mu, sigma, size=(num_stocks, num_samples))

def monte_carlo_simulation(num_stocks, num_samples, mu, sigma, weights):
    returns = generate_samples(num_stocks, num_samples, mu, sigma)
    portfolio_returns = np.sum(returns * weights, axis=0)
    return portfolio_returns

num_stocks = 4
num_samples = 10000
mu = np.array([0.12, 0.15, 0.08, 0.05]).reshape(4, 1)
sigma = np.array([0.2, 0.25, 0.15, 0.1]).reshape(4, 1)
weights = np.array([0.25, 0.25, 0.25, 0.25]).reshape(4, 1)

results = monte_carlo_simulation(num_stocks, num_samples, mu, sigma, weights)
print(results)

# Plot the results
plt.hist(results, bins=50, edgecolor='black')
plt.xlabel('Return')
plt.ylabel('Frequency')
plt.title('Monte Carlo Simulation Results')
plt.show()