function generateUUID() { // generated by ChatGPT
	// create an array of possible characters for the UUID
	var possibleChars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";

	// create an empty string that will be used to generate the UUID
	var uuid = "";

	// loop over the possible characters and append a random character to the UUID string
	for (var i = 0; i < 36; i++) {
		uuid += possibleChars.charAt(Math.floor(Math.random() * possibleChars.length));
	}

	// return the generated UUID
	return uuid;
}