//This code was generated by ChatGPT.

#include <iostream>
#include <vector>

using namespace std;

// Function to print the Tic Tac Toe board
void printBoard(const vector<vector<char>>& board) {
    // Print the board using ASCII characters
    cout << "-------------" << endl;
    for (int i = 0; i < 3; i++) {
        cout << "| ";
        for (int j = 0; j < 3; j++) {
            cout << board[i][j] << " | ";
        }
        cout << endl;
        cout << "-------------" << endl;
    }
}

int main() {
    // Initialize the Tic Tac Toe board
    vector<vector<char>> board(3, vector<char>(3, ' '));

    // Game loop
    bool isX = true;  // Flag to track the current player
    int moves = 0;    // Counter for total moves played

    while (moves < 9) {
        // Print the current state of the board
        printBoard(board);

        // Determine the current player
        char currentPlayer = isX ? 'X' : 'O';

        // Get the player's move input
        int row, col;
        cout << "Player " << currentPlayer << ", enter your move (row column): ";
        cin >> row >> col;

        // Update the board with the player's move
        board[row][col] = currentPlayer;

        // Toggle the player
        isX = !isX;
        moves++;
    }

    // Print the final state of the board
    printBoard(board);

    cout << "Game Over!" << endl;

    return 0;
}