"""
Generated by ChatGPT. 
"""
import csv
import sys

months_dict = {
    'ene': '01',
    'feb': '02',
    'mar': '03',
    'abr': '04',
    'may': '05',
    'jun': '06',
    'jul': '07',
    'ago': '08',
    'sep': '09',
    'oct': '10',
    'nov': '11',
    'dic': '12'
}

filename = sys.argv[1]

with open(filename, 'r') as input_file, open('ynab.csv', 'w', newline='') as output_file:
    reader = csv.DictReader(input_file)
    writer = csv.writer(output_file)
    writer.writerow(['Date', 'Payee', 'Category', 'Memo', 'Outflow', 'Inflow'])

    for row in reader:
        fecha = row['Fecha'].lower().split('/')
        mes = months_dict[fecha[1]]
        fecha_ynab = fecha[0] + '/' + mes + '/' + fecha[2]

        memo = row['Nota']

        monto = float(row['Monto'].replace(',', '.'))

        if monto < 0:
            outflow = str(-monto)
            inflow = ''
        else:
            outflow = ''
            inflow = str(monto)

        writer.writerow([fecha_ynab, '', '', memo, outflow, inflow])

print('Se ha completado la conversión del archivo ' + filename)