function numDashes(string) { // returns number of dashes in a string, generated by chatgpt
    // Use a regular expression to match all dash characters
    const dashes = string.match(/-/g);
    // Return the number of dashes found, or 0 if there are no matches
    return dashes ? dashes.length : 0;
}