/**
 *
 * The Below code is Optimal and generated by copilot
 */
function nextGreatestLetter(letters: string[], target: string): string {
    let low: number = 0,
      high: number = letters.length;
    while (low < high) {
      let mid: number = Math.floor(low + (high - low) / 2);
      if (letters[mid] <= target) low = mid + 1;
      else high = mid;
    }
    return letters[low % letters.length];
  }