  // Explosion effect crates multiple particles from the original one displayed on screen.
  // Uses random() function to create different colors
  // Generated by ChatGPT
  explode() {
    this.exploded = true;
    for (let i = 0; i < 100; i++) {
        const particleVel = p5.Vector.random2D().mult(random(1, 5));
        const particleColor = [random(255), random(255), random(255)];
        this.particles.push(new Particle(this.pos.x, this.pos.y, particleVel, particleColor));
    }
}
// end of ChatGPT generation