# This code is generated by Chatgpt
from music21 import pitch


def adjust_to_c_major(note_name):
    c_major_scale = ["C", "D", "E", "F", "G", "A", "B"]

    # Check if note_name is valid
    try:
        given_pitch = pitch.Pitch(note_name)
    except:
        # Return a default note
        return "C4"

    if given_pitch.name in c_major_scale:
        return note_name

    # Find closest C note
    up = given_pitch.transpose(1)
    down = given_pitch.transpose(-1)

    if up.name in c_major_scale:
        return up.nameWithOctave
    elif down.name in c_major_scale:
        return down.nameWithOctave
    else:
        return note_name
