from datetime import datetime, timedelta

# This is an iCalendar file creator -- generated by ChatGPT
def create_icalendar_file(name, email, appointment_date, appointment_time):
    # Format appointment date and time
    appointment_datetime = datetime.strptime(f"{appointment_date} {appointment_time}", "%Y-%m-%d %I:%M %p")

    # Create iCalendar content
    icalendar_content = f"""BEGIN:VCALENDAR
VERSION:2.0
BEGIN:VEVENT
SUMMARY:Dentist Appointment - {name}
DESCRIPTION:Booking for {name} ({email})
DTSTART:{appointment_datetime.strftime('%Y%m%dT%H%M%S')}
DTEND:{(appointment_datetime + timedelta(minutes=30)).strftime('%Y%m%dT%H%M%S')}
LOCATION:Dentist Office
ORGANIZER:MAILTO:toothcheck.app@gmail.com
SEQUENCE:0
BEGIN:VALARM
TRIGGER:-PT15M
DESCRIPTION:Reminder
ACTION:DISPLAY
END:VALARM
END:VEVENT
END:VCALENDAR
"""

    # Write the iCalendar content to a file
    with open('appointment.ics', 'w') as file:
        file.write(icalendar_content)