def convert_strings_to_numbers(data):
    """
    Generated by ChatGPT :)
    """
    if isinstance(data, dict):
        # If it's a dictionary, apply the function recursively to its values
        return {key: convert_strings_to_numbers(value) for key, value in data.items()}
    elif isinstance(data, list):
        # If it's a list, apply the function recursively to its elements
        return [convert_strings_to_numbers(item) for item in data]
    elif isinstance(data, str):
        # If it's a string, try converting it to a number
        try:
            return int(data)
        except ValueError:
            try:
                return float(data)
            except ValueError:
                # If it's not a valid number, leave it as it is
                return data
    else:
        # If it's neither a dictionary, list, nor string, leave it as it is
        return data