// class is fully generated by ChatGPT:
class SeededRandom {
    constructor(seed) {
        this.seed = seed;
    }

    rand() {
        // Constants for the LCG
        const a = 1664525;
        const c = 1013904223;
        const m = 2 ** 32;

        // Update the seed and return a random number between 0 and 1
        this.seed = (a * this.seed + c) % m;
        return this.seed / m;
    }
}
