#This python script was generated by chatGPT to change the name of the cards in the list since they were name like "2-C.png"
import os

def rename_files_with_full_names(directory):
    # Dictionary to map single letters to full words for suits
    suit_map = {
        'C': 'Clubs',
        'D': 'Diamonds',
        'H': 'Hearts',
        'S': 'Spades'
    }

    # Dictionary to map single letters to full words for face cards
    face_card_map = {
        'J': 'Jack',
        'Q': 'Queen',
        'K': 'King',
        'A': 'Ace'
    }

    # Renaming files
    for filename in os.listdir(directory):
        if filename.endswith(".png"):
            parts = filename.split('-')
            if len(parts) == 2:
                face, suit = parts

                # Replace suit and face card abbreviations
                suit = suit_map.get(suit[0], suit)
                face = face_card_map.get(face, face)

                new_filename = f"{face}-{suit}.png"
                os.rename(os.path.join(directory, filename), os.path.join(directory, new_filename))
                print(f"Renamed {filename} to {new_filename}")

# Replace 'cards' with the path to your folder
directory = "cards"
rename_files_with_full_names(directory)