# generated by chatgpt

def nth_palindrome(n):
    if n < 10:
        return n

    length = 1
    count = 9

    while n > count:
        length += 1
        if length % 2 == 0:
            count += 9 * 10**((length // 2) - 1)
        else:
            count += 9 * 10**(length // 2)
    
    count -= 9 * 10**((length // 2) - (length % 2 == 0))
    offset = n - count - 1

    if length % 2 == 0:
        first_half = 10**((length // 2) - 1) + offset
        return int(str(first_half) + str(first_half)[::-1])
    else:
        first_half = 10**(length // 2) + offset
        return int(str(first_half) + str(first_half)[:-1][::-1])

N = int(input())
print(nth_palindrome(N-1))