// Test case 1: Normal array of positive numbers
console.log(sum([1, 2, 3, 4, 5])); 
// Expected output: 15

// Test case 2: Array containing negative numbers
console.log(sum([-1, -2, -3, -4, -5])); 
// Expected output: -15

// Test case 3: Empty array
console.log(sum([])); 
// Expected output: 0

// Test case 4: Array containing both positive and negative numbers
console.log(sum([10, -10, 5, -5, 15])); 
// Expected output: 15

// Test case 5: Array with floating point numbers
console.log(sum([1.5, 2.5, 3.5])); 
// Expected output: 7.5

/**
 * Do not modify this file ! 
 * This file is read & written by GPT-3
 * 
 * Every Doclet with an @autogenerated tag is from GPT-3
 */

/**
 * @autogenerated
 * @summary Greet someone with a personalized message
 * 
 * @desc This function logs a personalized message to the console, based on the name provided as an argument.
 * 
 * @param {string} name The name to include in the personalized message.
 */
function Greet(name) {
    console.log(`Hello ${name}`);
}

/** 
 * @autogenerated
 * @summary Calculates the sum of all elements of an array
 * 
 * @param {number[]} arr The array of numbers to sum
 * 
 * @returns {number} The sum of all elements of the array
 */
function sum(arr) {
    let sum = 0;
    
    for (let i = 0; i < arr.length; i++)
        sum += arr[i];
    
    return sum;
}