#include <iostream>
#include <fstream>
#include <string>

using namespace std;
int currentYear = 2023;


// this code was generated by chatGPT
// it was modified to suit our case
const int daysInMonth[] = {0, 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31};

int getDaysInMonth(int year, int month)
{

    // Adjust February for leap years
    if (month == 2)
    {
        if ((year % 4 == 0 && year % 100 != 0) || (year % 400 == 0))
        {
            return 29; // Leap year
        }
        else
        {
            return 28; // Non-leap year
        }
    }

    return daysInMonth[month];
}