//Generated by Chatgpt:
function getAllAlphabets() {
    return Array.from({ length: 26 * 2 }, (_, index) => {
      const charCode = index < 26 ? 97 + index : 65 + index - 26;
      return String.fromCharCode(charCode);
    });
  }