/* Get Current date
 Generated by ChatGPT 4.0
@ author chat.openai.com */
function getCurrentDate() {
    const currentDate = new Date();
    const date = currentDate.toISOString().split('T')[0];
  
    return date;
  }