import java.util.Stack;

public class PythonFixIndentAction {
    //Code generated by chatGPT:)
    public static String fixIndentation(String pythonCode) {
        Stack<Integer> indentStack = new Stack<>();
        String[] lines = pythonCode.split("\n");
        StringBuilder fixedCode = new StringBuilder();
        int previousIndent = 0;
        for (String line : lines) {
            int currentIndent = line.length() - line.replaceAll("^[\t ]*", "").length();
            // check if the current line has less indentation than the previous line
            if (currentIndent < previousIndent) {
                // if so, pop the indentation stack until the current indentation level is found
                while (indentStack.size() > 0 && currentIndent < indentStack.peek()) {
                    indentStack.pop();
                    //fixedCode.append("\n");
                }
            }
            // add the appropriate number of tabs or spaces to the fixed code
            for (int i = 0; i < indentStack.size(); i++) {
                fixedCode.append("    ");
            }
            // add the current line to the fixed code, with leading whitespace removed
            fixedCode.append(line.replaceAll("^[\t ]*", "") + "\n");
            // if the current line ends with a colon, add the next indentation level to the stack
            if (line.endsWith(":")) {
                indentStack.push(currentIndent + 4);
            }
            previousIndent = currentIndent;
        }
        return fixedCode.toString();
    }
}
