// Generated by ChatGPT as I'm not a regex expert
const compressHTML = (htmlString) =>
    htmlString
      .replace(/>\s+|\s+</g, (m) => m.trim()) // Remove spaces around tags
      .replace(/(\r\n|\n|\r)\s*/gm, '') // Remove all newlines and spaces starting a newline
      .trim();