#include <iostream>
#include "Autocomplete.h"

int main() {
    Autocomplete autocomplete;
    autocomplete.insert("bin");
    autocomplete.insert("ball");
    autocomplete.insert("ballet");

    std::vector<std::string> suggestions;

    suggestions = autocomplete.getSuggestions("b");
    for (std::string s : suggestions) {
        std::cout << s << " ";
    }
    std::cout << std::endl;

    suggestions = autocomplete.getSuggestions("ba");
    for (std::string s : suggestions) {
        std::cout << s << " ";
    }
    std::cout << std::endl;

    suggestions = autocomplete.getSuggestions("bal");
    for (std::string s : suggestions) {
        std::cout << s << " ";
    }
    std::cout << std::endl;

    suggestions = autocomplete.getSuggestions("balle");
    for (std::string s : suggestions) {
        std::cout << s << " ";
    }
    std::cout << std::endl;

    return 0;
}

// Main.cpp generated by ChatGPT, May 15, 2023, OpenAI, https://chat.openai.com/chat.