def get_size_in_bytes(obj, print_size=True):
    """
    Generated by ChatGPT
    """
    if isinstance(obj, torch.Tensor):
        size_in_bytes = obj.element_size() * obj.nelement()
    elif isinstance(obj, np.ndarray):
        size_in_bytes = obj.nbytes
    else:
        raise TypeError("Object should be a PyTorch Tensor or a numpy array.")

    if print_size:
        print(f"Size of the object: {size_in_bytes:.2e} bytes")

    return size_in_bytes