// DEEP MERGE OBJECTS, a function generated by chatGPT where its essentially merges all of the keys of both of these objects to ensure that all of them end up in newly created object which we then set to transformation config
export const deepMergeObjects = (obj1: any, obj2: any) => {
    if (obj2 === null || obj2 === undefined) {
      return obj1;
    }
  
    let output = { ...obj2 };
  
    for (let key in obj1) {
      if (obj1.hasOwnProperty(key)) {
        if (
          obj1[key] &&
          typeof obj1[key] === "object" &&
          obj2[key] &&
          typeof obj2[key] === "object"
        ) {
          output[key] = deepMergeObjects(obj1[key], obj2[key]);
        } else {
          output[key] = obj1[key];
        }
      }
    }
  
    return output;
  };