import numpy as np


def process_jiang(raw_data, frequencies):     # generated by chatGPT
    num_frequencies = raw_data.shape[1]
    num_measurements = raw_data.shape[0]
    frequencies = np.repeat(frequencies, num_measurements)
    processed_data = np.zeros((num_frequencies * num_measurements, 3))
    processed_data[:, 0] = frequencies
    processed_data[:, 1:] = raw_data.reshape(-1, 2)
    return processed_data