import serial
import pyaudio
import numpy as np

# helper function to play a short tone (found from various sources on the web and reconceptualized)
pya = pyaudio.PyAudio()
sample_rate = 44100
freq = 2000  # hz
long_beep = np.sin(2 * np.pi * freq * np.linspace(0, 1, 44100)).astype(np.float32)
stream = pya.open(sample_rate, channels=1, format=pyaudio.paFloat32, output=True)


def beep(isLong=False):
    if isLong:
        stream.write(long_beep)
    else:
        stream.write(long_beep[0:5000])


s = serial.Serial("COM5", 115200)
code = ""  # these are our state.  At any given time, we could have a partial code, partial word, or partial sentence
word = ""
sentence = ""
decoder = {  # generated by chatgpt
    ".-": "A",
    "-...": "B",
    "-.-.": "C",
    "-..": "D",
    ".": "E",
    "..-.": "F",
    "--.": "G",
    "....": "H",
    "..": "I",
    ".---": "J",
    "-.-": "K",
    ".-..": "L",
    "--": "M",
    "-.": "N",
    "---": "O",
    ".--.": "P",
    "--.-": "Q",
    ".-.": "R",
    "...": "S",
    "-": "T",
    "..-": "U",
    "...-": "V",
    ".--": "W",
    "-..-": "X",
    "-.--": "Y",
    "--..": "Z",
    ".----": "1",
    "..---": "2",
    "...--": "3",
    "....-": "4",
    ".....": "5",
    "-....": "6",
    "--...": "7",
    "---..": "8",
    "----.": "9",
    "-----": "0",
    ".-.-.-": "."
}

while True:

    symbol = s.read().decode()
    if symbol == ".":
        beep(False)
    elif symbol == "-":
        beep(True)

    print(symbol, sep="")  # mostly for debugging, but doesn't hurt anything

    # if the symbol is not a space or a new line, add it to the code
    if (symbol != " ") and (symbol != "\n"):
        code += symbol

    else:  # the symbol is a space or a new line
        if code in decoder:  # code is valid, decode and add to the word
            letter = decoder[code]
            print(code, letter)
            word += letter
        else:
            print("invalid symbol")
        code = ""  # in any case, clear the code

        if symbol == "\n":  # if the symbol is a new line, check the word
            if word == "XX":
                with open("message.txt", "w") as f:
                    f.write(sentence)
                    f.close()  # close the file
                    stream.close()  # must kill pyaudio
                    quit()  # exits the program
            else:  # tack on the word
                sentence += " " + word
            # in any case clear it
            word = ""