/*
 (Generated by ChatGPT)
 Problem:
   Write a C++ program that sorts a list of names in the format "NameNumber", where Name is a string of letters and Number is an integer appended at the end of the string. The names should be sorted by the integer number first, and then by the Name in ascending order.
 
   Input:
         "AlbanyPatriawan12"
         "GamerTag12"
         "Rammy4"
 
   Output:
         "Rammy4"
         "Albany Patriawan12"
         "GamerTag12"
*/

vector<string> tdd::Sort the string array with the shape of "name + number" in ascending order. If the numbers are the same, sort by name in ascending order, and return the sorted array(vector<string> names) {
    sort(names.begin(), names.end(), compareNames);
    return names;
};