import numpy as np
import matplotlib.pyplot as plt
"""
This script is used to create a pulsar pattern for the Conway's game of life.
The board is a 3D numpy array with the following shape: (x, y, 1). The first two dimensions represent the region 
where the gun is drawn and the third dimension stores the state (alife or dead).
The pattern itself was generated by ChatGPT
The function returns the glider gun and is used in the main program upon calling the draw_pattern function.
The function must be called "create_pattern" and must return the array with the pattern in order to be used.
"""

def create_pattern(): #initiation done by chatGPT
    size = 15
    pulsar = np.zeros((size, size), dtype=int)

    # Coordinates for the pulsar pattern
    pulsar_coords = [(1, 4), (1, 5), (1, 6), (1, 10), (1, 11), (1, 12),
                     (3, 2), (3, 7), (3, 9), (3, 14),
                     (4, 2), (4, 7), (4, 9), (4, 14),
                     (5, 2), (5, 7), (5, 9), (5, 14),
                     (6, 4), (6, 5), (6, 6), (6, 10), (6, 11), (6, 12),
                     (8, 4), (8, 5), (8, 6), (8, 10), (8, 11), (8, 12),
                     (9, 2), (9, 7), (9, 9), (9, 14),
                     (10, 2), (10, 7), (10, 9), (10, 14),
                     (11, 2), (11, 7), (11, 9), (11, 14),
                     (13, 4), (13, 5), (13, 6), (13, 10), (13, 11), (13, 12)]

    # Set pulsar pattern cells to 1
    for x, y in pulsar_coords:
        pulsar[x, y] = 1
    #print ('pulsar created')
    return pulsar