function getTime() { // generated by ChatGPT
	var currentDate = new Date();
	var options = {
		hour12: true,
		hour: "numeric",
		minute: "numeric"
	};
	var timeString = currentDate.toLocaleTimeString("default", options);
	return timeString
}
