/* isBackgroundTooDarkOrBright - Checks if the background is bright, dark or normal */
/* FUNCTION GENERATED BY CHATGPT! */
function isBackgroundTooDarkOrBright() {
    // Get the RGB values from the main element as string
    const computedStyle = getComputedStyle(main);
    const backgroundColor = computedStyle.backgroundColor;

    // Convert the background color to RGB components
    const rgb = backgroundColor.match(/\d+/g);
    const r = parseInt(rgb[0]);
    const g = parseInt(rgb[1]);
    const b = parseInt(rgb[2]);

    // Calculate the perceived brightness using the formula
    const brightness = (r * 299 + g * 587 + b * 114) / 1000;

    // Define a threshold for darkness and brightness
    const darkThreshold = 125; // Adjust as needed
    const brightThreshold = 200; // Adjust as needed

    // Check if the brightness is too dark or too bright
    if (brightness < darkThreshold) {
        return "dark";
    } else if (brightness > brightThreshold) {
        return "bright";
    } else {
        return "normal";
    }
}
