##Generated by ChatGPT
##To solve this problem, we can first create a list of ranges from the input, where each range is represented as a tuple of two integers (the start and end of the range). Then, we can iterate over each pair of ranges in the list and check if one range fully contains the other. If it does, we can increment a counter by 1. Finally, we can return the counter as the result.

##Here is some example code that demonstrates how we can solve this problem:

##This solution will have a time complexity of O(n^2), where n is the number of ranges in the input, as we need to iterate over each pair of ranges in the list. This should be efficient enough for most inputs.

# Read input and create list of ranges
input = open('/Users/../Desktop/Advent-Of-Code/2022/input.txt','r')

ranges = []
for line in input:
  print(line)
  start, end = map(int, line.split('-'))
  ranges.append((start, end))

# Initialize counter
counter = 0

# Iterate over each pair of ranges
for r1, r2 in ranges:
  # Check if r1 fully contains r2 or vice versa
  if r1[0] <= r2[0] and r1[1] >= r2[1]:
    counter += 1
  elif r2[0] <= r1[0] and r2[1] >= r1[1]:
    counter += 1

# Return counter as result
print (counter)