  // The next function is generated by Chatgpt
  function extractCSVDataFromHTML(Mydocument) {
    const table = Mydocument.querySelector("table.waffle"); // Assuming the table has the "waffle" class
    const data = [];
    if (!table) {
      console.error("CSV table not found.");
      return { data };
    }
    // Extract data rows from the table body
    const dataRows = table.querySelectorAll("tbody tr");
    dataRows.forEach((row) => {
      const rowData = [];
      const tdElements = row.querySelectorAll("td");
      tdElements.forEach((td) => {
        rowData.push(td.textContent.trim());
      });
      data.push(rowData);
    });

    return data;
  }