#include "base64.h"

#include <Arduino.h>

const std::string BASE64_CHARS PROGMEM = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";

// code generated by ChatGPT
std::string base64_encode(const uint8_t* input, size_t input_length)
{
  std::string encoded;
  encoded.reserve(((input_length + 2) / 3) * 4);

  for (size_t i = 0; i < input_length; i += 3)
  {
    unsigned int c = input[i];
    c <<= 8;
    if ((i + 1) < input_length) {
      c |= input[i + 1];
    }
    c <<= 8;
    if ((i + 2) < input_length) {
      c |= input[i + 2];
    }

    encoded.push_back(BASE64_CHARS[(c >> 18) & 0x3F]);
    encoded.push_back(BASE64_CHARS[(c >> 12) & 0x3F]);
    if (i + 1 < input_length) {
      encoded.push_back(BASE64_CHARS[(c >> 6) & 0x3F]);
    } else {
      encoded.push_back('=');
    }
    if (i + 2 < input_length) {
      encoded.push_back(BASE64_CHARS[c & 0x3F]);
    } else {
      encoded.push_back('=');
    }
  }

  return encoded;
}