//code generated by chatgpt to extract fileId from url.
function getFileIdFromUrl(url) {
    // Define a regular expression to match the file ID in the URL
    const regex = /\/upload\/v\d+\/([^/]+)\./;
  
    // Execute the regex on the URL
    const match = url.match(regex);
  
    // Check if a match was found and return the file ID
    if (match && match[1]) {
      return match[1];
    } else {
      // Return null or an appropriate value if no match was found
      return null;
    }
  }
  