def merge_commands(content):
    """
     Merge similar latex math commands in the content.

     The merge_mapping was generated by chatgpt from the math commands frequencies
     """
    merge_mapping = {
        # Merging font styles
        '\\mathcal': '\\mathcal',
        '\\mathfrak': '\\mathcal',
        '\\mathbf': '\\mathbf',
        '\\mathit': '\\mathbf',
        '\\mathrm': '\\mathrm',

        # Merging logical and set theoretical symbols
        '\\subset': '\\subset',
        '\\subseteq': '\\subset',
        '\\supset': '\\supset',
        '\\supseteq': '\\supset',
        '\\notin': '\\notin',
        '\\not\\in': '\\notin',
        '\\neg': '\\neg',
        '\\lnot': '\\neg',
        '\\forall': '\\forall',
        '\\exists': '\\exists',

        # Merging algebra symbols
        '\\times': '\\times',
        '\\cdot': '\\times',
        '\\circ': '\\circ',
        '\\bullet': '\\circ',
        '\\oplus': '\\oplus',
        '\\star': '\\oplus',
        '\\otimes': '\\otimes',
        '\\diamond': '\\otimes',

        # Merging miscellaneous symbols
        '\\to': '\\to',
        '\\gets': '\\to',
        '\\rightarrow': '\\to',
        '\\leftarrow': '\\to',
        '\\leadsto': '\\leadsto',
        '\\longrightarrow': '\\leadsto',
        '\\leftrightarrow': '\\leftrightarrow',
        '\\longleftrightarrow': '\\leftrightarrow',
        '\\iff': '\\leftrightarrow',
        '\\Leftrightarrow': '\\leftrightarrow',
        '\\mod': '\\bmod',
        '\\bmod': '\\bmod'
    }
    for old_cmd, new_cmd in merge_mapping.items():
        content = content.replace(old_cmd, new_cmd)
    return content