# Extract files not in the csv file from the folderA to folderB
# THIS CODE IS Generated BY ChatGPT and Copliot
# Caution!: Need to install shutil(pip)

import os
import csv
import shutil

folderA = "path/to/folderA" #Has all the files
csv_file = "path/to/test.csv" #List of the files to be excluded
folderB = "path/to/folderB" #Empty folder. Extracted files will be copied here

# Read the filenames from the CSV file
filenames = []
with open(csv_file, "r") as file:
    reader = csv.reader(file)
    next(reader)  # skip the header row
    for row in reader:
        filenames.append(row[0])

# Copy all files from folderA to folderB that are not in the CSV file
for file in os.listdir(folderA):
    if file not in filenames:
        src = os.path.join(folderA, file)
        dst = os.path.join(folderB, file)
        shutil.copy2(src, dst)