/** 
 * Alphabetically sort an array of objects by a key
 * @param {Array} array - The array of objects to sort
 * @param {String} key - The key to sort by
 * @returns {Array} - The sorted array
*/
export default function(array, key) {
    // Sort an array of objects by a key
    // Usually will be the canonical
    // Generated by ChatGPT

    if (!Array.isArray(array) || array.length === 0) {
        return [];
    }

    if (!array[0].hasOwnProperty(key)) {
        throw new Error(`The key "${key}" does not exist in the objects.`);
    }

    return array.slice().sort((a, b) => {
        const valueA = a[key].toLowerCase(); // Convert to lowercase for case-insensitive sorting
        const valueB = b[key].toLowerCase();
        
        if (valueA < valueB) {
        return -1;
        }
        
        if (valueA > valueB) {
        return 1;
        }
        
        return 0;
    });
}