//Following two function generated by chatGPT
// Similar to the hexToFloat, can you write me one for uint32_t and int32_t?
uint32_t hexToUnsignedInt(const std::string& hexStr) {
    uint32_t value;
    std::stringstream ss(hexStr);
    ss >> std::hex >> value;
    return value;
}