//Generated by ChatGPT
// Function to convert a float to a hexadecimal string    
std::string floatToHex(float floatValue) {
    // Create an output string stream with hexadecimal formatting and no showbase
    std::ostringstream oss;
    oss << std::hex << std::noshowbase;

    // Interpret the bits of the float as an unsigned integer
    auto value = *reinterpret_cast<unsigned int*>(&floatValue);

    // Set the width to 8 characters and fill with zeroes
    oss << std::setw(8) << std::setfill('0') << value;

    // Return the formatted string
    return oss.str();
}