// Code between <BEGIN> and <END> is generated by ChatGPT
// <BEGIN>

#include <stdio.h>
#include <stdlib.h>

// Structure to represent a node in the priority queue
typedef struct {
    int data;
    int priority;
} Node;

// Structure to represent the priority queue
typedef struct {
    Node* array;
    int capacity;
    int size;
} PriorityQueue;

// Function to initialize a priority queue
PriorityQueue* initializePriorityQueue(int capacity) {
    PriorityQueue* pq = (PriorityQueue*)malloc(sizeof(PriorityQueue));
    pq->array = (Node*)malloc(capacity * sizeof(Node));
    pq->capacity = capacity;
    pq->size = 0;
    return pq;
}

// Function to swap two nodes
void swapNodes(Node* a, Node* b) {
    Node temp = *a;
    *a = *b;
    *b = temp;
}

// Function to heapify the priority queue
void heapify(PriorityQueue* pq, int index) {
    int smallest = index;
    int left = 2 * index + 1;
    int right = 2 * index + 2;

    if (left < pq->size && pq->array[left].priority < pq->array[smallest].priority) {
        smallest = left;
    }

    if (right < pq->size && pq->array[right].priority < pq->array[smallest].priority) {
        smallest = right;
    }

    if (smallest != index) {
        swapNodes(&pq->array[index], &pq->array[smallest]);
        heapify(pq, smallest);
    }
}

// Function to insert a node into the priority queue
void enqueue(PriorityQueue* pq, int data, int priority) {
    if (pq->size == pq->capacity) {
        printf("Priority queue is full. Cannot enqueue.\n");
        return;
    }

    int index = pq->size;
    pq->array[index].data = data;
    pq->array[index].priority = priority;

    int parent = (index - 1) / 2;
    while (index > 0 && pq->array[index].priority < pq->array[parent].priority) {
        swapNodes(&pq->array[index], &pq->array[parent]);
        index = parent;
        parent = (index - 1) / 2;
    }

    pq->size++;
}

// Function to dequeue the node with the highest priority
Node dequeue(PriorityQueue* pq) {
    if (pq->size == 0) {
        printf("Priority queue is empty. Cannot dequeue.\n");
        Node emptyNode = {0, 0};
        return emptyNode;
    }

    Node root = pq->array[0];
    pq->array[0] = pq->array[pq->size - 1];
    pq->size--;

    heapify(pq, 0);

    return root;
}

// Function to check if the priority queue is empty
int isEmpty(PriorityQueue* pq) {
    return pq->size == 0;
}

// Function to print the elements of the priority queue
void printPriorityQueue(PriorityQueue* pq) {
    printf("Priority Queue: ");
    for (int i = 0; i < pq->size; i++) {
        printf("(%d, %d) ", pq->array[i].data, pq->array[i].priority);
    }
    printf("\n");
}

// Function to free the memory allocated for the priority queue
void freePriorityQueue(PriorityQueue* pq) {
    free(pq->array);
    free(pq);
}
// <END>




int main() {
    // Example usage
    PriorityQueue* pq = initializePriorityQueue(10);

    enqueue(pq, 5, 2);
    enqueue(pq, 3, 1);
    enqueue(pq, 7, 3);
    enqueue(pq, 1, 5);

    printPriorityQueue(pq);

    while (!isEmpty(pq)) {
        Node node = dequeue(pq);
        printf("Dequeued: (%d, %d)\n", node.data, node.priority);
    }

    freePriorityQueue(pq);

    return 0;
}