def print_fixed_width_table(table: dict[str, list[Any]]) -> None:
    """
    Please note that this function was entirely generated by ChatGPT.
    """
    # Get the list of keys and values from the dictionary
    keys = list(table.keys())
    values = list(table.values())

    # Transpose the values list to get rows instead of columns
    values = list(zip(*values))

    # Calculate the maximum width of each column
    widths = []
    for i in range(len(keys)):
        widths.append(max(len(str(x[i])) for x in values + [keys]))

    # Print the header
    print(" ".join("{:{}}".format(x, w) for x, w in zip(keys, widths)))

    # Print each row
    for row in values:
        print(" ".join("{:{}}".format(x, w) for x, w in zip(row, widths)))
