import re


def replacePhoneNumbers(self, msg):
    # Phone number regex generated by chatGPT
    pattern = re.compile(r'\b(?:\+\d{1,2}\s?)?(\d{1,4}[-.\s]?)?\(?\d{1,4}\)?[-.\s]?\d{1,9}[-.\s]?\d{1,9}\b')
    return pattern.sub('[PHONE_NUM]', msg)