/**
 * generated by ChatGPT
 */
export const arabicToEnglishNumbers = (str: string) => {
    const arabicNums = ["٠", "١", "٢", "٣", "٤", "٥", "٦", "٧", "٨", "٩"];
    const chars = str.split("");
    const converted = chars
      .map((char: string) => {
        const index = arabicNums.indexOf(char);
        return index !== -1 ? index : char;
      })
      .join("");
    return converted;
  };