// Generated by chatgpt
std::string to_string(const Jack::ParseTree& parseTree, int indent = 0) {
  std::string result;

  // Print the token information if available
  if (!parseTree.tok.value.empty()) {
    result += std::string(indent, ' ') + '\"' + parseTree.tok.value + "\"";
  } else {
    // Print the type of the node
    result +=
        std::string(indent, ' ') + Jack::to_string(parseTree.type) + ": [\n";
    // Recursively process child nodes
    for (auto child = parseTree.children.begin();
         child < parseTree.children.end(); child++) {
      result += to_string(*child, indent + 2);
      if (child + 1 < parseTree.children.end()) {
        result += ",\n";
      } else {
        result += "]";
      }
    }
  }

  return result;
}