# Methods generated by ChatGPT to manage the colors : convertion and adjustment (make the color lighter)
def adjustColor(color):
    hsv = rgbToHsv(color)

    # Reduce the saturation
    hsv[1] = max(0, hsv[1] - COLOR_ADJUSTMENT_FACTOR)

    # Convert the color back to RGB
    rgb = hsvToRgb(hsv)

    return rgb