    // generated by ChatGPT
    function generateCronExpression () {
        // 生成每天的半夜2-4点之间的小时值（随机选择）
        const hour = Math.floor(Math.random() * 3) + 2
  
        // 生成每小时的随机分钟值（0到59之间的随机数）
        const minute = Math.floor(Math.random() * 60)
  
        // 构建 cron 表达式
        return `${minute} ${hour} * * *`
      }
  