def trim_strings(array: List[str]) -> List[str]:
    """
    :param array: The array of translated article tag.

    Iterate through the article tag to check if there's backsticks generated by chatgpt.
    """

    new_array = []

    for chunk in array:
        if chunk.startswith('```'):
            chunk = chunk[3:]
        if chunk.endswith('```'):
            chunk = chunk[:-3]

        new_array.append(chunk)

    return new_array