#include "Project.h"
#include <sys/stat.h>
#include "OpenXLSX.hpp"

void splitComma(string& str, vector<string>& vect) {
    stringstream ss(str);
    std::string s;
    while (!ss.eof()) {
        std::string s;
        if (std::getline(ss, s, ',')) {
            // Generated by chatGPT
            // Remove leading and trailing whitespace from the extracted string
            size_t start = s.find_first_not_of(' ');
            size_t end = s.find_last_not_of(' ');
            if (start != std::string::npos && end != std::string::npos) {
                vect.push_back(s.substr(start, end - start + 1));
            }
        }
    }
}