package org.real.temp;

public class Answer {

    /**
     * Create a pose matrix representing a rotation about a given axis.
     * Generated by ChatGPT-4, we make no assumptions about its correctness.
     *
     * @param angleDeg Rotation angle in degrees.
     * @param axis     Axis to rotate about, must be one of 'X', 'Y', or 'Z'.
     * @return A 4x4 pose matrix representing the rotation.
     */
    public static double[][] createRotMatrix(double angleDeg, String axis) {
        // Convert angle from degrees to radians
        double angleRad = Math.toRadians(angleDeg);

        // Define the rotation matrix based on the specified axis
        double[][] rotationMatrix;
        switch (axis.toLowerCase()) {
            case "x":
                rotationMatrix = new double[][]{
                    {1, 0, 0, 0},
                    {0, Math.cos(angleRad), -Math.sin(angleRad), 0},
                    {0, Math.sin(angleRad), Math.cos(angleRad), 0},
                    {0, 0, 0, 1}
                };
                break;
            case "y":
                rotationMatrix = new double[][]{
                    {Math.cos(angleRad), 0, Math.sin(angleRad), 0},
                    {0, 1, 0, 0},
                    {-Math.sin(angleRad), 0, Math.cos(angleRad), 0},
                    {0, 0, 0, 1}
                };
                break;
            case "z":
                rotationMatrix = new double[][]{
                    {Math.cos(angleRad), -Math.sin(angleRad), 0, 0},
                    {Math.sin(angleRad), Math.cos(angleRad), 0, 0},
                    {0, 0, 1, 0},
                    {0, 0, 0, 1}
                };
                break;
            default:
                throw new IllegalArgumentException("Invalid axis. Must be one of 'X', 'Y', or 'Z'.");
        }

        return rotationMatrix;
    }

    public static void main(String[] args) {
        // Example usage
        double angleDeg = 90; // Example angle in degrees
        String axis = "X"; // Example axis

        double[][] rotationMatrix = createRotMatrix(angleDeg, axis);
        printMatrix(rotationMatrix);
    }

    private static void printMatrix(double[][] matrix) {
        for (double[] row : matrix) {
            for (double value : row) {
                System.out.printf("%.2f ", value);
            }
            System.out.println();
        }
    }
}