//generated by chatgpt on 7/20/23
std::string getLastPartOfFilepath(const std::string& filepath) {
    // Find the last occurrence of the path separator character (e.g., '/')
    size_t lastSeparator = filepath.find_last_of("/\\");

    if (lastSeparator != std::string::npos) {
        // Extract the substring starting from the position after the last separator
        return filepath.substr(lastSeparator + 1);
    }

    // If no separator is found, return the entire filepath
    return filepath;
}
