//Shuffles a string in a random way:
function shuffleString(str) {
    var arr = str.split('');
    var len = arr.length;
    for (var i = len - 1; i > 0; i--) {
      var j = Math.floor(Math.random() * (i + 1));
      [arr[i], arr[j]] = [arr[j], arr[i]]; // Use array destructuring for swapping
    }
    return arr.join('');
  }
  //generated by Chatgpt