function numLetters(string) { // returns number of letters in a string, generated by chatgpt
    // Use a regular expression to match all letters (both uppercase and lowercase)
    const letters = string.match(/[A-z]/g);
    // Return the number of letters found, or 0 if there are no matches
    return letters ? letters.length : 0;
}