function numNumbers(string) { // returns number of numbers in a string, generated by chatgpt
    // Use a regular expression to match all numeric characters
    const numbers = string.match(/[0-9]/g);
    // Return the number of numbers found, or 0 if there are no matches
    return numbers ? numbers.length : 0;
}