#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "hello.h"

const char* getHello() {
    return "hello world";
}

// code generated by chatgpt
char* return_string(const char* input) {
    // Allocate memory for the new string
    char* result = malloc(strlen(input) + 1);

    // Check if memory allocation was successful
    if (result == NULL) {
        perror("Memory allocation failed");
        exit(EXIT_FAILURE);
    }

    // Copy the input string to the result
    strcpy(result, input);

    return result;
}