# Code Generated by ChatGPT from the prompt: "Write a Python implementation of the Crystals-Kyber
# decryption algorithm with comments."

def decrypt(n, q, secret_key, ciphertext):
    # Initialize the plaintext polynomial
    plaintext = [0] * n

    for i in range(n):
        # Calculate the contribution from the secret key
        plaintext[i] = ciphertext[i]

        # Subtract the contribution of the secret key
        plaintext[i] -= secret_key[i]

        # Modulo q
        plaintext[i] %= q

    return plaintext