/**
 * generated by ChatGPT
 */
const arabicToEnglishNumbers = (str: string) => {
    const arabicNums = ["٠", "١", "٢", "٣", "٤", "٥", "٦", "٧", "٨", "٩"];
    const chars = str.split("");
    const converted = chars
        .map((char: string) => {
            const index = arabicNums.indexOf(char);
            return index !== -1 ? index : char;
        })
        .join("");
    return converted;
};

/**
 * generated by ChatGPT
 */
export const zNumber = z.preprocess((value) => {
    if (typeof value === "string") {
        const converted = arabicToEnglishNumbers(value);
        const parsedNumber = parseFloat(converted);
        return isNaN(parsedNumber) ? value : parsedNumber;
    }
    return value;
}, z.number({invalid_type_error: "must be a number"}));

export const getLocaleDirection = (locale: string) => {
    const RTL_LOCALES = ["ar", "he", "fa", "ur"];
    const language = locale?.split("-")[0];
    return RTL_LOCALES.includes(language) ? "rtl" : "ltr";
};