import re


def is_phrase_in_string(phrase, string): #CHECK - possible optimisations, maybe without re, generated by chatgpt
    # Escape special characters in the phrase
    escaped_phrase = re.escape(phrase)
    # Replace spaces with \s+ to allow for any whitespace
    escaped_phrase = escaped_phrase.replace(r'\ ', r'\s+')
    # Construct the pattern with word boundaries
    pattern = r'\b' + escaped_phrase + r'\b'
    return re.search(pattern, string) is not None