// Helper function generated by ChatGPT
export function getFileExtension(file_name: string) {
    const regex = /(?:\.([^.]+))?$/; // Matches the last dot and everything after it
    const match = regex.exec(file_name);
    if (match && match[1]) {
      return match[1];
    }
    return ''; // No file extension found
  }