// generated by ChatGPT
export function getCombinations(array) {
    const result = [];
    for (let i = 0; i < array.length; i++) {
      for (let j = i + 1; j < array.length; j++) {
        result.push([array[i], array[j]]);
      }
    }
    return result;
  }