//Partly generated by ChatGpt
//Function to change position of flags and convert to Hex (reverse)
std::string convFlags(unsigned int flags) {
    unsigned int newFlags = 0;
    for (unsigned int i = 0; i<5; i++) {
        if(flags & (1<<i)) {
            newFlags |= (1 << (4-i));
        }
    }
    std::stringstream ss;
    // Output the flags as a hex number, padded with zeros up to the necessary number of digits (2 for 8 bits)
    ss  << std::setfill('0') << std::setw(2) << std::hex << (newFlags & 0x1F); // Mask to get only the least significant 5 bits
    return ss.str();

}

