    // Toroidal vector difference function generated by ChatGPT
    toroidalDiff(other, w, h) {
        let dx = this.x - other.x;
        let dy = this.y - other.y;

        // Handle wraparound for the x dimension
        if (Math.abs(dx) > w / 2) {
            dx = dx > 0 ? dx - w : dx + w;
        }

        // Handle wraparound for the y dimension
        if (Math.abs(dy) > h / 2) {
            dy = dy > 0 ? dy - h : dy + h;
        }

        return [dx, dy];
    }