# Generated By ChatGPT DGL
# Write Python code that generates all possible combinations of 8 characters, 
# with each character consisting of either a lowercase or uppercase English letter and 
# also has a function to check the XOR sum of the 0th, 3rd, 6th characters, 
# the XOR sum of the 1st, 4th, 7th characters, 
# and the XOR sum of the 2nd and 5th characters. 
# Also add function to check sha1 hash of the combination startwith 0xff7b948953ac
# Use Pytorch framework to use GPU
# Generated By ChatGPT DGL
# Write Python code that generates all possible combinations of 8 characters, 
# with each character consisting of either a lowercase or uppercase English letter and 
# also has a function to check the XOR sum of the 0th, 3rd, 6th characters, 
# the XOR sum of the 1st, 4th, 7th characters, 
# and the XOR sum of the 2nd and 5th characters. 
# Also add function to check sha1 hash of the combination startwith 0xff7b948953ac
# Use Pytorch framework to use GPU

import torch
import string
import hashlib
import time
import itertools



def check_xor_sum(combination):
    xor_sum_0_3_6 = combination[:, 0].int(
    ) ^ combination[:, 3].int() ^ combination[:, 6].int()
    xor_sum_1_4_7 = combination[:, 1].int(
    ) ^ combination[:, 4].int() ^ combination[:, 7].int()
    xor_sum_2_5 = combination[:, 2].int() ^ combination[:, 5].int()
    return (xor_sum_0_3_6 == 0x6b) & (xor_sum_1_4_7 == 0x76) & (xor_sum_2_5 == 0x12) 