# Code is generated by ChatGPT
import json
import matplotlib.pyplot as plt

def read_log(log_file_path):
    # Open the log file for reading
    with open(log_file_path, "r") as file:
        # Read each line in the file
        lines = file.readlines()

    # Initialize empty lists to store the question
    test_acc1_list = []
    train_loss_list = []

    # Iterate over each line in the log file
    for line in lines:
        # Parse the line as JSON
        data = json.loads(line)

        # Extract the test_acc1 and train_loss values and append them to the lists
        test_acc1_list.append(data["test_acc1"])
        train_loss_list.append(data["train_loss"])

    # Return the lists of test_acc1 and train_loss values
    return train_loss_list, test_acc1_list