function getFontSizeFromID(id) {
    const el = document.getElementById(id);
    const fontSize = parseInt(window.getComputedStyle(el).fontSize);
    return fontSize;
}

function getScrollbarWidth() {
    // This function was generated by ChatGPT-3
    // Create a dummy element with a scrollbar
    const scrollDiv = document.createElement('div');
    scrollDiv.style.width = '100px';
    scrollDiv.style.height = '100px';
    scrollDiv.style.overflow = 'scroll';

    // Append the dummy element to the document
    document.body.appendChild(scrollDiv);

    // Calculate the scrollbar width
    const scrollbarWidth = scrollDiv.offsetWidth - scrollDiv.clientWidth;

    // Remove the dummy element from the document
    document.body.removeChild(scrollDiv);

    return scrollbarWidth;
}

export { getFontSizeFromID, getScrollbarWidth };