# generated by chatgpt
from scipy.special import comb

'''
I have a jar with red and blue balls. 
There are 31 red balls and 7500 blue balls. 
I randomly take out 15 balls from the jar. 
What is the probability that at least 3 of the balls are red?
This code actually works.
'''


def probability_at_least_k_red(k, n, N_red, N_blue):
    probability = 0
    for i in range(k, n + 1):
        probability += (comb(n, i) * comb(N_red, i) * comb(N_blue, n - i)) / comb(N_red + N_blue, n)
    return probability


def at_least_N_red(num_red):
    # Given information
    N_red_balls = 31
    N_blue_balls = 7500
    total_draws = 15

    # Calculate probability of at least num_red red balls
    probability_at_least_N_red = probability_at_least_k_red(num_red, total_draws, N_red_balls, N_blue_balls)

    print(
        f"The probability of drawing at least {num_red} red balls out of {total_draws} draws is: {probability_at_least_N_red:.6f}")


at_least_N_red(2)
