//
// Created by User on 1/9/2024.
//

#ifndef LED_PROJECT_COLORS_H
#define LED_PROJECT_COLORS_H
#include <stdint.h>
//generated by chatgpt
enum Color {
    RED,
    GREEN,
    BLUE,
    YELLOW,
    MAGENTA,
    CYAN,
    WHITE,
    BLACK,
    ORANGE,
    PURPLE,
    PINK,
    BROWN,
    // Add more colors as needed
    NUM_COLORS
};

// Structure to represent RGB color
struct RGB {
    int red;
    int green;
    int blue;
};

// Array of RGB values corresponding to each color
struct RGB colorValues[NUM_COLORS] = {
        {255, 0, 0},      // RED
        {0, 255, 0},      // GREEN
        {0, 0, 255},      // BLUE
        {255, 255, 0},    // YELLOW
        {255, 0, 255},    // MAGENTA
        {0, 255, 255},    // CYAN
        {255, 255, 255},  // WHITE
        {0, 0, 0},        // BLACK
        {255, 165, 0},    // ORANGE
        {128, 0, 128},    // PURPLE
        {255, 192, 203},  // PINK
        {165, 42, 42},    // BROWN
        // Add more color values as needed
};
#endif //LED_PROJECT_COLORS_H