// Jest test cases for countLetters function
describe('countLetters', () => {
    test('should return the correct count for a string with only letters', () => {
        const result = numLetters('HelloWorld');
        expect(result).toBe(10); // 'HelloWorld' contains ten letters
    });

    test('should return 0 for a string with no letters', () => {
        const result = numLetters('12345!@#$%');
        expect(result).toBe(0); // '12345!@#$%' contains no letters
    });

    test('should return the correct count for a string with mixed characters', () => {
        const result = numLetters('H3ll0 W0rld!');
        expect(result).toBe(7); // 'H3ll0 W0rld!' contains seven letters
    });

    test('should return the correct count for a string with uppercase and lowercase letters', () => {
        const result = numLetters('JavaScript');
        expect(result).toBe(10); // 'JavaScript' contains ten letters
    });

    test('should return 0 for an empty string', () => {
        const result = numLetters('');
        expect(result).toBe(0); // An empty string contains no letters
    });
});
function numLetters(string) { // returns number of letters in a string, generated by chatgpt
    // Use a regular expression to match all letters (both uppercase and lowercase)
    const letters = string.match(/[A-z]/g);
    // Return the number of letters found, or 0 if there are no matches
    return letters ? letters.length : 0;
}