#!/usr/bin/env python3
# This was generated by ChatGPT after I constructed the regexp using
# Google Bard and gave it to ChatGPT.  It parses an email in a string
# and prints the components to stdout.  I had to fix the "sep" part of
# the regexp by hand

import re

pattern = r"""
^                                       # start of string/line
(?P<username>[a-zA-Z0-9_.+-]+)          # username
(?P<sep>)@                              # @ symbol
(?P<hostname>[a-zA-Z0-9-]+\.[a-zA-Z]+)  # hostname
$                                       # end of string/line
"""

email = "john@example.com"

match = re.match(pattern, email, re.VERBOSE)
if match:
    print("Email address is valid.")
    print("Username:", match.group("username"))
    print("Hostname:", match.group("hostname"))
else:
    print("Invalid email address.")