// Helper function generated by ChatGPT
export function removeFileExtension(file_name: string) {
    const lastDotIndex = file_name.lastIndexOf('.');
    if (lastDotIndex !== -1) {
      return file_name.slice(0, lastDotIndex);
    }
    return file_name; // No file extension found
  }