// Generated by ChatGPT. Prompt: "I want to move a server-side function in a django server to the client. Write a javascript equivalent to this code: def changedClef(self,id,clef="bass"):  
//        self_abc=self.get(id=id).abc
//        clef_index=self_abc.index("\nK:")
//        next_newline=self_abc.index("\n",clef_index+1)
//        injection=" clef={}".format(clef)
//        return "".join((self_abc[:next_newline],injection,self_abc[next_newline:]))"

function changedClef(abc, clef = "bass") {
    let clef_index = abc.indexOf("\nK:");
    let next_newline = abc.indexOf("\n", clef_index + 1);
    let injection = ` clef=${clef}`;
    let out=`${abc.substring(0, next_newline)}${injection}${abc.substring(next_newline)}`;
    console.log(out)
    return out;
}