def validate_email():
    email = request.json.get('value')

    # Check if the email field is empty
    if not email.strip():  # Catch empty strings after stripping whitespace
        return jsonify('No email provided.'), 400

    # Check if email is already in use
    if User.query.filter_by(email=email).first():
        return jsonify('This email is already in use.'), 400

    # Validate email format using regex (generated by ChatGPT)
    email_regex = r'^[a-zA-Z0-9.!#$%&\'*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*\.[a-zA-Z]{2,6}$'
    if not re.match(email_regex, email.strip()):
        return jsonify('Invalid email format.'), 400

    return jsonify({'error': False}), 200