import matplotlib.pyplot as plt
import numpy as np

"""
Generated by ChatGPT GPT-4
"""

def draw_square_lattice(size, spacing):
    x_points, y_points = np.meshgrid(np.arange(0, size, spacing), np.arange(0, size, spacing))
    plt.scatter(x_points, y_points, color='blue')
    plt.gca().set_aspect('equal', adjustable='box')
    plt.title('Square Lattice of Points')
    plt.xlabel('x')
    plt.ylabel('y')
    plt.show()

lattice_size = 10
point_spacing = 1

draw_square_lattice(lattice_size, point_spacing)