def create_rot_matrix(angle_deg, axis):
    """
    Create a pose matrix representing a rotation about a given axis.
    Generated by ChatGPT-4, we make no assumptions about its correctness.

    Args:
        angle_deg (float): Rotation angle in degrees.
        axis (str): Axis to rotate about, must be one of 'X', 'Y', or 'Z'.

    Returns:
        numpy.ndarray: 4x4 pose matrix representing the rotation.
    """
    # Convert angle from degrees to radians
    angle_rad = np.deg2rad(angle_deg)

    # Define the rotation matrix based on the specified axis
    if axis == 'x':
        rotation_matrix = np.array([[1, 0, 0, 0],
                                    [0, np.cos(angle_rad), -np.sin(angle_rad), 0],
                                    [0, np.sin(angle_rad), np.cos(angle_rad), 0],
                                    [0, 0, 0, 1]])
    elif axis == 'y':
        rotation_matrix = np.array([[np.cos(angle_rad), 0, np.sin(angle_rad), 0],
                                    [0, 1, 0, 0],
                                    [-np.sin(angle_rad), 0, np.cos(angle_rad), 0],
                                    [0, 0, 0, 1]])
    elif axis == 'z':
        rotation_matrix = np.array([[np.cos(angle_rad), -np.sin(angle_rad), 0, 0],
                                    [np.sin(angle_rad), np.cos(angle_rad), 0, 0],
                                    [0, 0, 1, 0],
                                    [0, 0, 0, 1]])
    else:
        raise ValueError("Invalid axis. Must be one of 'X', 'Y', or 'Z'.")

    return rotation_matrix
