
//Generated by ChatGPT
// Function to convert a hexadecimal string to a float
float hexToFloat(const std::string& hexStr) {
    // Convert the hexadecimal string to a uint32_t
    uint32_t intRep;
    std::stringstream ss;
    ss << std::hex << hexStr;
    ss >> intRep;

    // Reinterpret the bits of the integer as float
    float floatValue;
    std::memcpy(&floatValue, &intRep, sizeof(floatValue));
    return floatValue;
}
