import re


def processCol(col):
    # RegEx generated by ChatGPT
    col = [re.split(r',(?!(?:[^()]*\([^()]*\))*[^()]*\)) ', x)
            if type(x) is str else [] for x in col]
    for x in col:
        for i in range(len(x)-1, 1, -1):
            if "(" in x[i] and "(" not in x[i-1] and not x[i].startswith("("):
                x[i-1] = f"{x[i-1]} ({x[i].split(" (", 1)[1]}"
        for i in range(1, len(x)-1):
            if re.search(r"\([a-zA-Z]+\.", x[i]):
                print(x[i])
                print(x[i-1])
                search = list(re.finditer(r"([a-zA-Zß.][a-zA-Zß. ]+,\s)?\d{4},\s", x[i-1]))
                if search:
                    print(search[-1].group())
                    print(re.sub(r"\(([a-zA-Z]+\.)", fr"({search[-1].group()}\1", x[i]))
                    x[i] = re.sub(r"\(([a-zA-Z]+\.)", fr"({search[-1].group()}\1", x[i])
                # for i in search:
                #     print(i)
                # print(search.string if search else "")
                print()
    return col